### ISSUE TITLE
Can't find the mysql.h

### ISSUE THREAD

**Issue by 0x1306a94** [vapor/cmysql#10]
* Vapor Version: 2.0
* OS: Ubuntu 16.04 Mac 10.12.4
* OS Version: Ubuntu MySQL5.7 Mac MySQL5.7
* Vapor Toolbox Version: 

### Current Behavior
* perform `vapor build` command, to make mistakes `Shim.h file mysql.h I couldn't find it`
* Ubuntu platform to perform the same error
* I think you should refer to the following procedure

https://github.com/PerfectlySoft/Perfect-MySQL/blob/master/Package.swift
https://github.com/PerfectlySoft/Perfect-mysqlclient/blob/master/module.modulemap
https://github.com/PerfectlySoft/Perfect-mysqlclient-Linux/blob/master/module.modulemap

**Comment by tanner0101** [comment]
Use

```sh
brew install cmysql
```

or

```sh
sudo apt-get install cmysql
```

Instructions for adding Vapor's brew tap and APT repo are available here: https://docs.vapor.codes/2.0/getting-started/install-on-macos/
