### ISSUE TITLE
Cannot build CMySQL module on Heroku

### ISSUE THREAD

**Issue by vzsg** [vapor/cmysql#8]
The current master uses a custom pkg-config file to work around SPM limitations, which is great for regular Linux systems and Docker, but not so much for Heroku, where apt-get is not available.

Previously in vapor/vapor#954, I've been trying to install the cmysql deb package manually with an [Aptfile](https://github.com/vapor/vapor/files/905085/Aptfile.txt) and [heroku-buildpack-apt](https://github.com/heroku/heroku-buildpack-apt), which installs the packages under [`/app/.apt`](https://github.com/vapor/vapor/files/905092/files.txt) and sets a bunch of [environment variables](https://github.com/vapor/vapor/files/905100/env.txt), but I couldn't get the Swift buildpack to pick it up.

In an ideal world, the dependency should Just Work on Heroku without adding extra buildpacks.

Build output and Package.swift: [gist](https://gist.github.com/vzsg/f96fa669780a30a42e06b59660c75d9c)

**Comment by BrettRToomey** [comment]
Status on this?

**Comment by vzsg** [comment]
I didn't do anything with it myself.

**Comment by tanner0101** [comment]
We need a heroku ninja to help us fix this before 2.0 is released.

**Comment by jdmcd** [comment]
I currently have around 15-20 apps running on Heroku instances, all running on MySQL and I'm pretty concerned about this. I'd love to collaborate with someone to find a solution.
